モックサーバーを追加
trisets/trisets pull request #16
Opened 2022-11-05 03:08 UTC by terra-d

ブラウザ⇔Web APIとの通信をモックすることで、バックエンドにつながなくてもフロントエンド開発ができる状態にした。

適当ですが、`/sandbox`にサンプルがあります

2022-11-08 14:25 UTC, habutaso requested changes
コメントしました。

2022-11-10 16:08 UTC, terra-d commented on package.json
> +    "msw": "^0.47.4",
`devDependencies`のみにしました
dependenciesはproductionで使用するパッケージのみに絞るようにしたい（前は逆のことを言ってましたが心変わりしました

2022-11-10 16:10 UTC, terra-d commented on mocks/browser.ts
> +// eslint-disable-next-line import/no-extraneous-dependencies
[d60a7ad](https://github.com/trisets/trisets/pull/16/commits/d60a7ad3a1089cb22fe851e29c6422f79ce79fcd)
により、この行は必要になりました

どこかでeslintの設定で、mswは` import/no-extraneous-dependencies`の例外リストに入れたい

2022-11-10 16:15 UTC, terra-d commented
#19 の対応が必要になってしまった・・・

2022-11-17 21:30 UTC, habutaso submitted a review, later dismissed

2022-11-19 09:18 UTC, merged